#!/usr/bin/env python
# -*- coding: utf-8 -*-
from TaxiFareModel.data import get_data
from TaxiFareModel.data import clean_data
from TaxiFareModel.trainer import Trainer
from sklearn.model_selection import train_test_split
df = get_data()
df=clean_data(df)
y = df["fare_amount"]
X = df.drop("fare_amount", axis=1)
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.15)
train=Trainer(X,y)
train.set_pipeline()
train.run()
print('rmse= ',train.evaluate(X_val,y_val))